version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn clean install
      - save_cache:
          paths:
            - .m2/
          key: dynamodb-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  release:
    docker:
      - image: sportebois/docker-alpine-aws-cli

    steps:
      - restore_cache:
          key: dynamodb-{{ .Environment.CIRCLE_WORKFLOW_ID }}

      - run: ls -al
      - run: aws s3 sync /home/circleci/.m2/repository/com/amazonaws/dynamodb-lock-client/1.2.0/ s3://bzion-varejo-mvn/release/com/amazonaws/dynamodb-lock-client/1.2.0/ --metadata-directive REPLACE --delete

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          context: Bzion
      - release:
          context: Bzion
          requires:
            - build
          filters:
            branches:
              only: master