version: 2.1

jobs:
  build:
    docker:
      - image: bzion/openjdk-awscli:8

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn clean install
      - run: aws s3 sync /home/circleci/.m2/repository/com/amazonaws/dynamodb-lock-client/1.2.0/ s3://bzion-mvn/release/com/amazonaws/dynamodb-lock-client/1.2.0/ --metadata-directive REPLACE --delete

workflows:
  version: 2
  build-release:
    jobs:
      - build:
          context: Bzion
          filters:
            branches:
              only: master